### ISSUE TITLE
getSubset: complexity limits?

### ISSUE THREAD

**Issue by cryptix** [arj03/ssb-secure-partial-replication#11]
I was wondering how we might constraint the complexity of invoicing these queries on another peer.

The first obvious thing I did is have a limit on the input json. I was also wondering about checking/limiting the length and depth of the logical operations AND and OR somehow but as long as this is implemented as combining bitmaps, it seems fairly lightweight.

**Comment by staltz** [comment]
> The first obvious thing I did is have a limit on the input json.

Isn't this the purpose of `options.pageSize`?

> I was also wondering about checking/limiting the length and depth of the logical operations AND and OR somehow but as long as this is implemented as combining bitmaps, it seems fairly lightweight.

Ah, are you predicting that some rogue remote peer could use this to create a very expensive operation for the local peer? That makes sense, we could limit it to something large enough to give freedom of expressing all sorts of things, but small enough to avoid such attacks. Maybe ~20 is a good limit?
