### ISSUE TITLE
plugin/handler group name?

### ISSUE THREAD

**Issue by cryptix** [arj03/ssb-secure-partial-replication#12]
Where do we add these methods in the muxrpc manifest?

I could see `partialReplication` as the plugin name but I don't have strong feelings on this.

```json

"partialReplication": {
  "getSubset": "source",
  "resolveIndexFeed": "source",
  "getTangle": "source"
}
```

**Comment by cryptix** [comment]
Ah, this then also proposes to replace the previous `getMessagesOfType` and `getFeed` methods from @arj03 first experiment in browser-core since they can be done with `getSubset`.

**Comment by staltz** [comment]
Sounds good to me!

**Comment by arj03** [comment]
Yes to partialReplication and the removal of the old methods.

**Comment by cryptix** [comment]
AFAIR we did this.
