### ISSUE TITLE
getSubset query data

### ISSUE THREAD

**Issue by cryptix** [arj03/ssb-secure-partial-replication#5]
I propose to change the query operation schema a little. This kind of dynamic _this could be a string or it could be an array of more stuff_, like done with `data` here, can be incredibly cumbersome to deal with in typed languages.

As an alternative, It's much simpler when these are differently named fields, like so:

```js
{
  op: 'and',
  operations: [
    { op: 'type', string: 'post' },
    { op: 'author', feed: '@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519' }
  ]
},
```

**Comment by arj03** [comment]
Sure, that works. I'll update the spec. Good input :)
