### ISSUE TITLE
rename getIndexFeed

### ISSUE THREAD

**Issue by cryptix** [arj03/ssb-secure-partial-replication#6]
the _get_ part seems confusing. It does not return an index feed or it's content. It returns what the messages in the index feed point to.

How about `resolveIndexFeed` ?

cc @staltz

**Comment by staltz** [comment]
cc'd the right person?

**Comment by arj03** [comment]
Fine by me. I'd also like to hear what @staltz thinks :)

**Comment by staltz** [comment]
I'll need more time to look at this properly. At the moment I have no idea what y'all talking about 😅

**Comment by arj03** [comment]
Also you are away, what if we punt this until you are back next week? It's just a name and you'll have to read a bunch of stuff to get the overview.

**Comment by cryptix** [comment]
Yea sorry, @staltz. I just pinged you because i like your approach to naming things.

This really isn't urgent.

**Comment by staltz** [comment]
Okay, I took a look at this repo and this issue.

> `getIndexFeed(feedId): source`
>
> `[{  msg: msg1, indexed: origMsg }, ...]`

What is the purpose of having both `msg` and `origMsg` together? Could we fetch these things in separate APIs? E.g. first fetch all the `msg`s (in the index feed) and then based on those results, fetch all the `origMsg`s? For the first part, that's just normal replication of a feed. The second part is not about "getting the index", it's about "retrieval" or "resolving", so cryptix's suggestion is good. The input to the second part could be all the (first part) `msg`s, or it could be the `feedId`. I'm not sure if a polymorphic function is a good idea for all languages, so better settle on either `resolveIndexMessages(msgs)` or `resolveIndexFeed(feedId)`. Depends on which one is more useful as an API.

**Comment by cryptix** [comment]
> Could we fetch these things in separate APIs? 

For only `msg`s you could already use `createHistoryStream`. I _think_ you want them together to say "yes, resolving msg1 leads me to the indexes origMsg" (cc @arj03)

**Comment by arj03** [comment]
Yes, I wanted to avoid clients doing two api calls as that is bad for performance. The use case for this api is light clients. For things like pubs or clients that store feeds in full they would be using normal replication methods like createhistorystream or getsubset.

**Comment by staltz** [comment]
Hmm, okay, thanks for the context. In that case, I can't think of a name better than `resolveIndexFeed`!
