### ISSUE TITLE
Improve EBT to only learn about the length of feeds

### ISSUE THREAD

**Issue by cryptix** [arj03/ssb-secure-partial-replication#9]
Related to #8, we discussed that it would be good to have a way to get the length of a set of feeds before starting to ingest unknown amounts of data.

Before we make `getSubSet` even more complicated (add reverse, limit 1 per author, splice out just the sequence of each feed via some `SELECT field` style stuff...) I proposed to tune EBT in a way that it _just_ does vector clock exchanges, not pushing all the messages eagerly.

This could be solved via a simple `no-messages: true` option in the duplex call arguments.

**Comment by arj03** [comment]
Now done with ssb-ebt 8
